# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CNC.ui'
#
# Created: Tue Jul 16 16:53:21 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import imageCapture
import cncBase

try:
    _fromUtf8 = QtCore.QString.fromUtf8  # @UndefinedVariable
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    cncBase = None

    def __init__(self, cncBase, *args, **kwargs):
        return object.__init__(self, *args, **kwargs)

    
    
    def captureImage(self):
        window = QtGui.QDialog()
        GUI = imageCapture.Ui_CaptureImageBox()
        GUI.setupUi(window)
        window.exec_()
        

    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1124, 647)
        MainWindow.setMinimumSize(QtCore.QSize(1124, 647))
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setWhatsThis(_fromUtf8(""))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_buttons = QtGui.QFrame(self.centralwidget)
        self.frame_buttons.setMinimumSize(QtCore.QSize(241, 0))
        self.frame_buttons.setMaximumSize(QtCore.QSize(241, 16777215))
        self.frame_buttons.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_buttons.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_buttons.setObjectName(_fromUtf8("frame_buttons"))
        self.layoutWidget = QtGui.QWidget(self.frame_buttons)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 231, 284))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_control = QtGui.QLabel(self.layoutWidget)
        self.label_control.setObjectName(_fromUtf8("label_control"))
        self.verticalLayout_2.addWidget(self.label_control)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.button_edit = QtGui.QPushButton(self.layoutWidget)
        self.button_edit.setMinimumSize(QtCore.QSize(98, 27))
        self.button_edit.setObjectName(_fromUtf8("button_edit"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.button_edit)
        self.horizontalLayout_2.addWidget(self.button_edit)
        self.button_delete = QtGui.QPushButton(self.layoutWidget)
        self.button_delete.setMinimumSize(QtCore.QSize(98, 27))
        self.button_delete.setObjectName(_fromUtf8("button_delete"))
        self.buttonGroup.addButton(self.button_delete)
        self.horizontalLayout_2.addWidget(self.button_delete)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_drawing = QtGui.QLabel(self.layoutWidget)
        self.label_drawing.setObjectName(_fromUtf8("label_drawing"))
        self.verticalLayout.addWidget(self.label_drawing)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.button_square = QtGui.QPushButton(self.layoutWidget)
        self.button_square.setMinimumSize(QtCore.QSize(98, 27))
        self.button_square.setMaximumSize(QtCore.QSize(101, 27))
        self.button_square.setObjectName(_fromUtf8("button_square"))
        self.buttonGroup.addButton(self.button_square)
        self.gridLayout.addWidget(self.button_square, 0, 1, 1, 1)
        self.button_line = QtGui.QPushButton(self.layoutWidget)
        self.button_line.setMinimumSize(QtCore.QSize(98, 27))
        self.button_line.setMaximumSize(QtCore.QSize(102, 27))
        self.button_line.setObjectName(_fromUtf8("button_line"))
        self.buttonGroup.addButton(self.button_line)
        self.gridLayout.addWidget(self.button_line, 0, 0, 1, 1)
        self.button_arc = QtGui.QPushButton(self.layoutWidget)
        self.button_arc.setEnabled(False)
        self.button_arc.setMinimumSize(QtCore.QSize(98, 27))
        self.button_arc.setMaximumSize(QtCore.QSize(101, 27))
        self.button_arc.setObjectName(_fromUtf8("button_arc"))
        self.buttonGroup.addButton(self.button_arc)
        self.gridLayout.addWidget(self.button_arc, 1, 1, 1, 1)
        self.button_freedraw = QtGui.QPushButton(self.layoutWidget)
        self.button_freedraw.setEnabled(False)
        self.button_freedraw.setMinimumSize(QtCore.QSize(98, 27))
        self.button_freedraw.setMaximumSize(QtCore.QSize(102, 27))
        self.button_freedraw.setFlat(False)
        self.button_freedraw.setObjectName(_fromUtf8("button_freedraw"))
        self.buttonGroup.addButton(self.button_freedraw)
        self.gridLayout.addWidget(self.button_freedraw, 2, 0, 1, 1)
        self.button_circle = QtGui.QPushButton(self.layoutWidget)
        self.button_circle.setEnabled(False)
        self.button_circle.setMinimumSize(QtCore.QSize(98, 27))
        self.button_circle.setMaximumSize(QtCore.QSize(102, 27))
        self.button_circle.setObjectName(_fromUtf8("button_circle"))
        self.buttonGroup.addButton(self.button_circle)
        self.gridLayout.addWidget(self.button_circle, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.frame_buttons)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShadow(QtGui.QFrame.Raised)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.frame_canvas = QtGui.QFrame(self.centralwidget)
        self.frame_canvas.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.frame_canvas.setStatusTip(_fromUtf8(""))
        self.frame_canvas.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_canvas.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_canvas.setObjectName(_fromUtf8("frame_canvas"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_canvas)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout.addWidget(self.frame_canvas)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 25))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuToolbars = QtGui.QMenu(self.menuView)
        self.menuToolbars.setObjectName(_fromUtf8("menuToolbars"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionSave.setIconVisibleInMenu(False)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionDrawing = QtGui.QAction(MainWindow)
        self.actionDrawing.setCheckable(True)
        self.actionDrawing.setChecked(True)
        self.actionDrawing.setObjectName(_fromUtf8("actionDrawing"))
        self.actionCapture_Image = QtGui.QAction(MainWindow)
        self.actionCapture_Image.setObjectName(_fromUtf8("actionCapture_Image"))
        self.actionDrawn_Item_List = QtGui.QAction(MainWindow)
        self.actionDrawn_Item_List.setObjectName(_fromUtf8("actionDrawn_Item_List"))
        self.actionControl = QtGui.QAction(MainWindow)
        self.actionControl.setCheckable(True)
        self.actionControl.setChecked(True)
        self.actionControl.setObjectName(_fromUtf8("actionControl"))
        self.actionItem_Tree = QtGui.QAction(MainWindow)
        self.actionItem_Tree.setCheckable(True)
        self.actionItem_Tree.setEnabled(False)
        self.actionItem_Tree.setObjectName(_fromUtf8("actionItem_Tree"))
        self.actionZoom_Extents = QtGui.QAction(MainWindow)
        self.actionZoom_Extents.setObjectName(_fromUtf8("actionZoom_Extents"))
        self.actionZoom_True_Size = QtGui.QAction(MainWindow)
        self.actionZoom_True_Size.setObjectName(_fromUtf8("actionZoom_True_Size"))
        self.actionZoom_2x = QtGui.QAction(MainWindow)
        self.actionZoom_2x.setObjectName(_fromUtf8("actionZoom_2x"))
        self.actionZoom_4x = QtGui.QAction(MainWindow)
        self.actionZoom_4x.setObjectName(_fromUtf8("actionZoom_4x"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuToolbars.addAction(self.actionDrawing)
        self.menuToolbars.addAction(self.actionControl)
        self.menuToolbars.addAction(self.actionItem_Tree)
        self.menuView.addAction(self.menuToolbars.menuAction())
        self.menuView.addAction(self.actionZoom_Extents)
        self.menuView.addAction(self.actionZoom_True_Size)
        self.menuView.addAction(self.actionZoom_2x)
        self.menuView.addAction(self.actionZoom_4x)
        self.menuTools.addAction(self.actionCapture_Image)
        self.menuTools.addAction(self.actionDrawn_Item_List)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        
        QtCore.QObject.connect(self.actionCapture_Image, QtCore.SIGNAL(_fromUtf8("triggered()")), self.captureImage)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Controller", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setStatusTip(QtGui.QApplication.translate("MainWindow", "I\'m your main window :D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_control.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">CONTROL</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.button_edit.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.button_delete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_drawing.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">DRAWING</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.button_square.setText(QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.button_line.setText(QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.button_arc.setText(QtGui.QApplication.translate("MainWindow", "Arc", None, QtGui.QApplication.UnicodeUTF8))
        self.button_freedraw.setText(QtGui.QApplication.translate("MainWindow", "Freedraw", None, QtGui.QApplication.UnicodeUTF8))
        self.button_circle.setText(QtGui.QApplication.translate("MainWindow", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuToolbars.setTitle(QtGui.QApplication.translate("MainWindow", "Toolbars", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.statusbar.setToolTip(QtGui.QApplication.translate("MainWindow", "This is the status bar", None, QtGui.QApplication.UnicodeUTF8))
        self.statusbar.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hi", None, QtGui.QApplication.UnicodeUTF8))
        self.statusbar.setAccessibleName(QtGui.QApplication.translate("MainWindow", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDrawing.setText(QtGui.QApplication.translate("MainWindow", "Drawing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCapture_Image.setText(QtGui.QApplication.translate("MainWindow", "Capture Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDrawn_Item_List.setText(QtGui.QApplication.translate("MainWindow", "Drawn Item List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionControl.setText(QtGui.QApplication.translate("MainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.actionItem_Tree.setText(QtGui.QApplication.translate("MainWindow", "Item Tree", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_Extents.setText(QtGui.QApplication.translate("MainWindow", "Zoom Extents", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_True_Size.setText(QtGui.QApplication.translate("MainWindow", "Zoom True Size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_2x.setText(QtGui.QApplication.translate("MainWindow", "Zoom 2x", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_4x.setText(QtGui.QApplication.translate("MainWindow", "Zoom 4x", None, QtGui.QApplication.UnicodeUTF8))

